### ISSUE TITLE
please enable netty-epoll or kqueue in addb-lettuce

### ISSUE THREAD

**Issue by hshs1103** [addb-swstarlab/addb-loader#1]
lettuce provides event handling like epoll or kqueue.(https://github.com/lettuce-io/lettuce-core/wiki/Native-Transports)

It seems that addb_lettuce does not currently use netty-epoll and kqueue.

For better performance, please provide the ability to use netty-epoll or netty-kqueue.

**Comment by arbc139** [comment]
I progress to setup pom.xml adding netty-related libraries.
```
<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-transport-native-epoll</artifactId>
    <version>4.1.38.Final</version>
    <classifier>linux-x86_64</classifier>
    <optional>true</optional>
</dependency>
<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-transport-native-kqueue</artifactId>
    <version>4.1.38.Final</version>
    <classifier>osx-x86_64</classifier>
    <optional>false</optional>
</dependency>
```

Please check this pull request.
